name: Auto Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  release:
    if: ${{ github.repository == 'casdoor/casdoor-rust-sdk' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: semantic-release-action/rust/.github/workflows/release-library.yml@v5
    with:
      disable-semantic-release-git: true
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_TOKEN }}
